// Field targets are laid out for a right-handed batter viewed from behind the
// striker, looking toward the bowler. The coordinates describe cricket regions,
// not arbitrary UI slots.
export const SHOT_TARGETS = [
  {
    id: 'cover-drive',
    label: 'Cover Drive',
    subLabel: 'Experience',
    path: '/experience',
    position: { x: 70, y: 49 },
    bezierControl: { cx1: 59, cy1: 61, cx2: 68, cy2: 51 },
    ariaLabel: 'Play a cover drive to navigate to Experience',
  },
  {
    id: 'pull-shot',
    label: 'Pull Shot',
    subLabel: 'Projects',
    path: '/projects',
    position: { x: 29, y: 57 },
    bezierControl: { cx1: 45, cy1: 66, cx2: 35, cy2: 59 },
    ariaLabel: 'Play a pull shot to navigate to Projects',
  },
  {
    id: 'straight-drive',
    label: 'Straight Drive',
    subLabel: 'Research',
    path: '/research',
    position: { x: 50, y: 31 },
    bezierControl: { cx1: 50, cy1: 53, cx2: 50, cy2: 38 },
    ariaLabel: 'Play a straight drive to navigate to Research',
  },
  {
    id: 'flick',
    label: 'Flick',
    subLabel: 'About',
    path: '/about',
    position: { x: 34, y: 50 },
    bezierControl: { cx1: 44, cy1: 63, cx2: 36, cy2: 54 },
    ariaLabel: 'Play a flick through mid-wicket to navigate to About',
  },
  {
    id: 'edge-to-slip',
    label: 'Edge to Slip',
    subLabel: 'Contact',
    path: '/contact',
    position: { x: 64, y: 43 },
    bezierControl: { cx1: 57, cy1: 57, cx2: 62, cy2: 46 },
    ariaLabel: 'Play an edge toward slip to navigate to Contact',
  },
  {
    id: 'defensive-block',
    label: 'Defence',
    subLabel: 'Overview',
    path: '/overview',
    position: { x: 50, y: 69 },
    bezierControl: { cx1: 52, cy1: 66, cx2: 51, cy2: 69 },
    ariaLabel: 'Play a defensive block to navigate to Overview',
  },
];
